/* Generated By:JavaCC: Do not edit this line. XapiLangConstants.java */
package org.xapagy.xapi.language.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XapiLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 103;
  /** RegularExpression Id. */
  int LABEL = 104;
  /** RegularExpression Id. */
  int OCTALINT = 105;
  /** RegularExpression Id. */
  int DECIMALINT = 106;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 107;
  /** RegularExpression Id. */
  int FLOATONE = 108;
  /** RegularExpression Id. */
  int FLOATTWO = 109;
  /** RegularExpression Id. */
  int STRING_DOUBLE_QUOTES = 110;
  /** RegularExpression Id. */
  int STRING_SINGLE_QUOTES = 111;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"/\"",
    "\":\"",
    "\"inx\"",
    "\"//\"",
    "\"none\"",
    "\"successor\"",
    "\"view\"",
    "\"fictional-future\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"$DebugHere\"",
    "\"$Documentation\"",
    "\"$--\"",
    "\"$CreateScene\"",
    "\"Current\"",
    "\"CloseOthers\"",
    "\"AddSummary\"",
    "\"RelatedAs\"",
    "\"With Instances\"",
    "\"->\"",
    "\"$ChangeScene\"",
    "\"$CheckPoint\"",
    "\"$Define\"",
    "\"$Include\"",
    "\"From\"",
    "\"IfNotDefined\"",
    "\"$CreateLinkType\"",
    "\"DirectionPaired\"",
    "\"Default\"",
    "\"Weight\"",
    "\"=\"",
    "\"With\"",
    "\"Reverse\"",
    "\"Regular\"",
    "\"$CreateLink\"",
    "\"{\"",
    "\"}\"",
    "\"==>\"",
    "\"$SetParameter\"",
    "\"$CreateParameter\"",
    "\"AM_INSTANCE\"",
    "\"AM_VI\"",
    "\"FOCUS_INSTANCE\"",
    "\"FOCUS_VI\"",
    "\"SHADOW_INSTANCE\"",
    "\"SHADOW_VI\"",
    "\"DRIVE\"",
    "\"$CreateEnergy\"",
    "\"Of\"",
    "\"Type\"",
    "\"E2S\"",
    "\"$PerformanceMeter\"",
    "\"$Create\"",
    "\"$Update\"",
    "\"Concept\"",
    "\"Area\"",
    "\"ConceptImpact\"",
    "\"Impacts\"",
    "\"ConceptOverlap\"",
    "\"Overlaps\"",
    "\"[\"",
    "\"]\"",
    "\"Verb\"",
    "\"MetaVerb\"",
    "\"Code\"",
    "\"Relation\"",
    "\"VerbImpact\"",
    "\"VerbOverlap\"",
    "\"Word\"",
    "\"For\"",
    "\"ActionVerb\"",
    "\"$DiffusionActivity\"",
    "\"Clear\"",
    "\"Composite\"",
    "\"Append\"",
    "\"To\"",
    "\"New\"",
    "\"DA\"",
    "\"Name\"",
    "\"Update\"",
    "\"Parameters\"",
    "\"$SpikeActivity\"",
    "\"SA\"",
    "\"$Observer\"",
    "\"Add\"",
    "\"Triggered-at\"",
    "\"Executing\"",
    "\"RemoveAll\"",
    "\"Remove\"",
    "\"$Print\"",
    "\"$Namespace\"",
    "\"Set\"",
    "\"Create\"",
    "\"Trace\"",
    "<ID>",
    "<LABEL>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<STRING_DOUBLE_QUOTES>",
    "<STRING_SINGLE_QUOTES>",
  };

}
